//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutAPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        public int crrCarreraId { get; set; }
        public string crrDescripcion { get; set; }
        public string crrObservacion { get; set; }
        public bool crrAnulado { get; set; }
        public Nullable<System.DateTime> crrFechaCreacion { get; set; }
        public int empEmpleadoIdCreador { get; set; }
        public System.DateTime crrFechaDesde { get; set; }
        public Nullable<System.DateTime> crrFechaHasta { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
