//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnockOutAPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Carreras = new HashSet<Carreras>();
        }
    
        public int empEmpleadoId { get; set; }
        public string empNombre { get; set; }
        public string empApellido { get; set; }
        public Nullable<System.DateTime> empFechaNacimiento { get; set; }
        public string empOrden { get; set; }
        public int tpeTipoEmpleadoId { get; set; }
        public Nullable<int> sexSexoId { get; set; }
        public int eteEstadoEmpleadoId { get; set; }
        public Nullable<int> paiPaisOrigenId { get; set; }
        public Nullable<int> proProvinciaOrigenId { get; set; }
        public Nullable<int> lnuLocalidadOrigenId { get; set; }
        public string empEmail { get; set; }
        public Nullable<bool> empEnLicenciaProlongada { get; set; }
        public string empObservaciones { get; set; }
        public Nullable<bool> empConFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carreras> Carreras { get; set; }
        public virtual Empleados Empleados1 { get; set; }
        public virtual Empleados Empleados2 { get; set; }
        public virtual Empleados Empleados11 { get; set; }
        public virtual Empleados Empleados3 { get; set; }
    }
}
